= Import future: Practical projects for parents and children to do together

== Proposal

=== Summary

I spend a good amount of time travelling around the country, teaching kids to code in Python. Parents will often contact me, asking me how they can help their kids learn to code at their side. They want to share something that gives them so much joy and opens so many doors, but many are uncertain where to start. 

There are books that teach children to code, but not every child can learn this way. Some might need to be able to ask questions. Some stay on task better when an adult is involved. Some may simply enjoy the activity better when doing it with someone else. 

This book not only teaches the child to code in Python, but it also teaches the parent *how* to help their child along. The book includes both lessons and projects that are intended for a student and expert to go over together. Each chapter provides pointers to the expert on where a student might get stuck and how best to help them, as well as completed code samples for the student to play with. All projects also start with stub code, which tends to be much less intimidating for a young learner to work with.

This book does assume that the parent is a developer, and teaches the child Python. There will be a brief introduction to Python for the parent coder who is more familiar with another language. However, a non-coder parent can also work through the exercises, provided they read the chapter as well. Even adults who do not code have the skill of being able to troubleshoot more quickly than a child.

=== Media

While this book would work just fine as a print book, I believe that presenting it at a mixed-media package would work better for the current generation of students and teachers. A video might be used to reinforce a concept. An embedded coding environment would give a chance for students to play with code, without having to type it in by hand. It would also enable a parent to read one of the sections meant just for them without waiting for the student to reliquish the book.
  
This would also enable us to give the student the assets required for the various projects without sending them to another website. They could click the link, download the files, and get started. 
