= Import future: Practical projects for parents and children to do together

== Proposal

=== Summary

I spend a good amount of time travelling around the country, teaching kids to code in Python. Parents will often contact me, asking me how they can help their kids learn to code at their side. They want to share something that gives them so much joy and opens so many doors, but many are uncertain where to start. 

There are books that teach children to code, but not every child can learn this way. Some might need to be able to ask questions. Some stay on task better when an adult is involved. Some may simply enjoy the activity better when doing it with someone else. 

This book not only teaches the child to code in Python, but it also teaches the parent *how* to help their child along. Each lesson includes pointers for the parent, a lesson for the child, a project for them both to complete, and code samples of how the code might be written.

This book does assume that the parent is a developer, and teaches the child Python. There will be a brief introduction to Python for the parent coder who is more familiar with another language.

=== Outline:

* Introduction for kids
** What is coding?
** Why code?
** Why Python?
** What are we going to be doing?
* Introduction for parents
** Who is this book for?
*** If you don't know Python...
** Hands on / Hands off
** Managing your expectations (yours and theirs!)
** The set-up
* Let's get started!
** Install Python
** Learn about IDLE
** Let's do some coding
*** In the shell
*** In a file
* Basics: numbers, strings, math
* Input and output
* If / else
* Loops: For and while
* Project - Number guessing game
** random.int
** if / elif / else
** Loops
* Dictionaries and lists
* Project - To-Do list
** Lists
** Input
** Saving to a file
* Importing modules
* Project - Haiku generator
** Lists
** Reading from a file
** random.choice
* Functions
* Project - Let's write [some dice game]
** random.int
** Loops
** Functions
* Project - Game: Guess that lyric
** Dictionary
** random.choice
** random.shuffle
* OOP
* Project - Game: Virtual pet!
** Time?
** functions
** OOP
* Using PyGame
* Project - Beatbox
** pygame.mixer
* Project - Game: Virtual pet revisited: Let's make it GUI
** PyGame
* Moving to the Internet
** HTML
** CSS
** Flask
*** Install
*** Quick test
* Project - Make a website
** Flask
** functions
* Project - Let's mess around with Minecraft!
** Minecraft
** mcpipy
* Project - Homework helper
** Google API
* Project - Game: Virtual pet revisited: Let's make it GUI
** PyGame
* Going mobile (possible)
* Project: Kivy game!
* What now? (For kids)
* What now? (For parents)

=== Media

While this book would work just fine as a print book, I believe that presenting it at a mixed-media package would work better for the current generation of students and teachers. A video might be used to reinforce a concept. An embedded coding environment would give a chance for students to play with code, without having to type it in by hand. It would also enable a parent to read one of the sections meant just for them without waiting for the student to reliquish the book.
  
This would also enable us to give the student the assets required for the various projects without sending them to another website. They could click the link, download the files, and get started. 
