== Loops

So far, we've learned how to store information, make Python do what we want, and have Python run certain bits of code only if something is true. Now, it's time to have Python repeat code!

=== What you need to know...

You should have a good handle on Boolean expressions! If you're not sure about them, go back read over that section, or check out the review video.

=== Notes for the grown-up

In this lesson, we're going to be going over loops. Once again, you might have to spend some extra time emphasizing the importance of code blocks and indentation in Python. You also might want to emphasize when you use one type of loop over another type of loop.

For loops often present a special kind of challenge for many students. It might take a few tries for them to understand what a loop variable is. You might notice that were not teaching lists in this lesson. Going to start off by simply using range. If a student seems rather precocious, you might want to give them a brief overview of what a list is. If you need some help with that, check out the review video in the lists chapter.

Be careful not to overwhelm the student. If they're just getting used to the idea of loops then go ahead and leave lists for later.

As for range, younger students may need help with understanding steps when it comes to playing with range. If they seem confused don't be shy about moving on. I can count on one hand the number of times I've had to give range more than two parameters. 

Also, we're going to be creating an infinite loop later in the chapter. You should probably make sure you know how to exit out of one of those! On most systems, Control + C will force Python to exit the loop. If that doesn't work, try Control + D.

=== Why use a loop?

If we didn't use loops to repeat code, then our code would be super long. If we wanted to do something five times, we'd have to have the same code, repeated five times. Maybe we would want to do something until something happened. How would we do that without loops? We would have to guess when something might happen, and repeat the code that many times!

==== Types of loops

There are two kinds of loops: conditional loops and counting loops. 

*Conditional loops* run until something happens. Maybe the user chooses to quit the program, or maybe the player slays the dragon. Maybe the dragon slays the player! Whatever the event, once it happens, the loop ends, and the program moves on.

*Counting loops* run a certain number of times. You might want to run a block of code five times (or a hundred times!). For example, you may want to give a player a certain number of tries to guess a number. After their guesses are used up, you can tell them that they lost.

=== Counting loops (for)

Let's start with counting loops. In Python, we call these `for` loops. They look like this:

[source,python]
----
for num in range(nums):
   code
   code
   code
----

`nums` is the number of times you want the loop to run. So, if you want to run the code block five times, you would say `range(5)`. 

`num` is the *loop variable*. Every time the loop runs, it's going to store a new value. Let's look at the following code. Run it and note what is printed out.

[source,python]
----
for num in range(10):
    print num
----

Python printed out the numbers zero through nine! Let's talk a bit more about what `range()` does.

==== Range

`range()` has one job: It has to give you a list of numbers. Try out the following code:

[source,python]
----
print range(5)
----

If you give `range()` just one number, then Python will give you a list of numbers, from zero to _one less_ than that number. Change the code above so that you get a list of numbers from zero to one hundred!

What if you don't want to start at zero? Easy! You can give `range()` two numbers. The first is where Python starts, and the second number is where Python will stop. Note, though, that Python still stops _one less_ than that number. Try this code:

[source,python]
----
print range(1, 10)
----

You should have gotten a list of numbers from one to nine. Can you change the numbers so that they go from one to ten? What happens if you reverse the numbers?

What if you only want odd numbers or even numbers, or if you want to count by fives? You can give `range()` three numbers, and Python will start at the first number and "step" up until it reaches the max number. Take a look at this code:

[source,python]
----
print range(1, 50, 2)
----

Python printed out a list of numbers, starting at one and stopping just short of 50. It only printed the odd numbers, though. How would you change this code to print out the even numbers? What about counting by fives?

You can also change the step number to a negative number. What happens when you run this?

[source,python]
----
print range(10, 0, -1)
----

You get a list of numbers, but this time starting at ten and going down to one! Can you change the code so that you get only even numbers?

==== Range and for loops

Now that you have a handle on what `range()` does, let's combine it with a `for` loop. Before you run the following code, guess what Python will print out.

[source,python]
----
for i in range(5):
    print "Hello!"
----

Python printed out five hellos, didn't it? What do you think this code will do?

[source,python]
----
for i in range(10):
    print "@" * i
----

You should have gotten a triangle made out of at symbols on your screen.  

Each time the code in the code block is run, that's called an *iteration*. It's important to know that word, because we're going to be using it quite a bit. So, if your `for` loop runs five times, it has five *iterations*. 

==== Skipping to the next item

`for` loops are great, but sometimes you want to skip to the next iteration. To do that, we use `continue`. 

Here's some code where we use `continue`. We want to print out the numbers zero through twenty, but if we can divide the number by three, then we want to print "Skip!"

[source,python]
----
for i in range(21):
    if i / 3 == i / 3.0:
        print "Skip!"
        continue
    print i
----

Let's talk about what this code is doing line by line.

*`for i in range(21)`*: This part should look familiar. We're going to iterate through the numbers zero through twenty.

*`if i / 3 == 1 / 3.0`*: Remember our issue with dividing whole numbers? We can use that to our advantage here! Let's say `i` is five. If we enter `5 / 3` into our intepreter, we get `1`. If we enter `5 / 3.0`, though, we get `1.6666667`. So five isn't divisible by three! 

*`print "Skip!"`*: We print skip if our current number is divisible by three...

*`continue`*: Once Python sees this, it knows that you don't want it to run the rest of the code in the for loop. It goes back to the beginning, rather than running the rest of the code in the block.

*`print i`*: If the number isn't divisible by three, then we print the number out.

`continue` is extremely useful for blocks of code that are long, or where there may be many instances where you want to continue to the next iteration.

==== Ending the loop early

Sometimes, you want to end a loop early. For example, you may be searching for a certain item. Once you find it, you don't want to keep going through every other item in the list. Your job is done! To do this, you use `break`. 

This time, let's use `break` to quit our for loop once we find a number that is divisible by both five and seven.

[source,python]
----
for i in range(1, 1000):
    if i / 5 == i / 5.0 and i / 7 == i / 7.0:
        print "Found it! It was:", i
        break
    print i, "doesn't work..."
----

If you run the code, you'll see that the loop stops at 35. Once we found our number, we didn't need to keep going, so we used `break` to stop the `for` loop early. This can be extremely useful if you have a bunch of reasons why you might want to break out of a loop.

=== Conditional loops (while)

`for` loops are great for when you want to run a block of code a certain number of times. But what if you don't know how many times you want to run something? What if you want to run some code until something happens? That's when you use a `while` loop.

A `while` loop looks like this:

[source,python]
----
while expression:
    code
    code
    code
----

While an expression is true, the code in the block will run (Just a reminder: an expression is something like `num == 5` or `books > 6`). Once that expression is false, Python will stop running that block of code.

Let's check out a `while` loop in action. This time, we're going to run a block of code until `num` is greater than five. 

[source,python]
----
num = 0
while num <= 5:
   print "Num is", num
   num = num + 1
----

When you run the code, Python prints out six lines of text, starting with "Num is 0" and ending with "Num is 5". What's going on here?

On the first iteration, `num` is zero. Zero is less than five, so the block of code is run. What happens during the last iteration? Well, `num` is five, so Python prints that out, then adds one to `num`. `num` is now six, which is *not* less than or equal to five, so Python doesn't run the code block.

==== Infinite loops!

If you're going to use a `while` loop, you need to make sure that you can actually get out of them! It's very easy to create something called an *infinite loop* if you're not paying attention. An infinite loop is one that will keep going, on and on, until you force the program to quit. They're not a good thing!

Let's take a look at what an infinite loop might look like. 

[source,python]
----
num = 0
while num <= 5:
   print "Num is", num
----

That looks almost like the code in the last section, but we forgot to add one to `num`. If we run this code, this is what we'll see:

[source,python]
----
Num is 0
Num is 0
Num is 0
Num is 0
Num is 0
Num is 0
...
-----

"Num is 0" will keep on printing until you force Python to stop. In IDLE, you do this by pressing control + C (this is the case for both Windows and Macs).

==== Skipping a turn

Just like `for` loops, you can use `continue` to move to the next iteration of your `while` loop. Here, we have a `while` loop that will run while `num` is less than 20. If `num` equals eleven, though, we want to print out "My favorite number!"

[source,python]
----
num = 0
while num < 20:
    num = num + 1
    if num == 11:
         print "My favorite!"
         continue
    print num
----

Note that eleven is never printed out. That's because we skip `print num` and move on to the next iteration of the `while` loop.

==== Getting out of a loop early

Again, just like `for` loops, we can get out of a loop early by using `break`. Let's change the code from the last section so that we break out of the loop when we get to my favorite number.

[source,python]
----
num = 0
while num < 20:
    num = num + 1
    if num == 11:
         print "My favorite!"
         break
    print num
----

This time, rather than printing out the numbers twelve through nineteen, Python stops once we hit eleven. Just like `for` loops, `break` is useful if there's many different reasons you might want to break out of a `while` loop. 

==== Try this!

In IDLE, open up a new file and enter this code:

[source,python]
----
num = 1
while num <= 100:
    print "Num is", num
    if num / 2 == num / 2.0:
        num = num + 2
        continue
    if num / 5 == num / 5.0:
        num = num - 1
        continue
    num = num + 1
----

When you run the code, watch what numbers are skipped. What happened when when `num` was ten? How about fifteen? What was added during each of those iterations?
